service:
  name: ${env:SERVICE_NAME}
  description: Description
provider:
  name: aws
  stage: ${env:STAGE}
  runtime: nodejs8.10
  profile: ${env:PROFILE}
  region: ${env:REGION}
  iamRoleStatements: ${file(config/iam.yml)}
  environment:
    REGION: ${env:REGION}
    SQS_ARN:
      Ref: SomeQueueName
    S3_BUCKET: ${env:S3_BUCKET_NAME}
custom:
  stages:
    - test
    - dev
    - prod
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: yarn
  dotenv:
    path: ./config/.env

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-stage-manager
  - serverless-dotenv-plugin

functions:
# Hello world
  helloWorld:
    handler: src/modules/hello-world/index.helloWorldHandler
    description: hello world
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: /hello-world
          method: get
# S3
  s3uploadImage:
    handler: src/modules/s3-upload-image/index.s3UploadImage
    description: hello world
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: /s3-upload-image
          method: post
  s3UploadImageSubscribe:
    handler: src/modules/s3-upload-image/index.s3UploadImageSubsribe
    events:
      - s3:
          bucket: ${env:S3_BUCKET_NAME}
          event: s3:ObjectCreated:*
# SNS
  snsSubscribe:
    handler: src/modules/sns/index.snsSubscribe
    events:
      - sns: ${env:SNS_TOPIC}
  snsPublish:
    handler: src/modules/sns/index.snsPublish
    events:
      - http:
          path: /sns-publish
          method: get
# SQS
  subscribe:
    handler: src/modules/sqs-publish-subscribe/index.subscribe
    description: Listens to sqs events
    memorySize: 128
    timeout: 120
    events:
      - sqs:
          batchSize: 3
          arn:
            Fn::GetAtt:
              - SomeQueueName
              - Arn

  publish:
    handler: src/modules/sqs-publish-subscribe/index.publish
    description: Listens to sqs events
    memorySize: 128
    timeout: 120
    events:
      - http:
          path: /publish
          method: get
resources:
  Resources:
    SomeQueueName:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${env:QUEUE_NAME}
        VisibilityTimeout: 130
        MessageRetentionPeriod: 260

