functions:
  subscribe:
    handler: src/modules/sqs-publish-subscribe/index.subscribe
    description: Listens to sqs events
    memorySize: 128
    timeout: 120
    events:
      - sqs:
          batchSize: 3
          arn:
            Fn::GetAtt:
              - SomeQueueName
              - Arn
  publish:
    handler: src/modules/sqs-publish-subscribe/index.publish
    description: Listens to sqs events
    memorySize: 128
    timeout: 120
    events:
      - http:
          path: /publish
          method: get

resources:
  Resources:
    SomeQueueName:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${env:QUEUE_NAME}
        VisibilityTimeout: 130
        MessageRetentionPeriod: 260
