- Effect: Allow
  Action:
    - lambda:InvokeFunction
  Resource: '*'
- Effect: Allow
  Action:
    - rekognition:CompareFaces
  Resource: '*'
- Effect: "Allow"
  Resource: "*"
  Action:
    - "sns:*"
- Effect: Allow
  Action:
    - s3:PutObject
    - s3:PutObjectAcl
    - s3:GetObject
    - s3:GetBucketNotification
    - s3:PutBucketNotification
  Resource:
    - arn:aws:s3:::${env:S3_BUCKET_NAME}/*
- Effect: Allow
  Action:
    - sqs:CreateQueue
    - sqs:DeleteMessage
    - sqs:GetQueueAttributes
    - sqs:GetQueueUrl
    - sqs:ReceiveMessage
    - sqs:SendMessage
  Resource:
    Fn::GetAtt:
      - SomeQueueName
      - Arn
- Effect: Allow
  Action:
    - logs:CreateLogGroup
    - logs:CreateLogStream
    - logs:PutLogEvents
    - logs:DescribeLogStreams
  Resource:
    Fn::Join:
      - ':'
      - - arn:aws:logs
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - log-group:/aws/lambda/*:*:*
- Effect: Allow
  Action:
    - cloudwatch:GetMetricData
  Resource: '*'
